In [2]:
import pandas as pd
import os 

subjects = [
    "03", "04", "05", "06", "08",
    "11", "12", "13", "15", "16",
    "17", "18", "19", "20", "22",
    "23", "24", "27", "31", "32",
    "33", "35", "37", "38", "43"
]

path = os.getcwd()
rows = []

for sub_id in subjects:
        for level in range( 1, 5 ):
            if level == 1:
                runs = ['01', '07', '12']
            elif level == 2:
                runs = ['03', '08', '10']
            elif level == 3:
                runs = ['02', '05', '11']
            elif level == 4:
                runs = ['04', '06', '09']
            for run_id in runs:
                df = pd.read_csv(path + f"/data_ils/cp0{sub_id}/0{sub_id}_time_s/0{sub_id}_time_s_level-0{level}_run-0{run_id}_dat.csv", 
                                 index_col=False)
                
                n_samples = len(df)
                minutes = n_samples / 60.0

                rows.append({
                     "subject":sub_id,
                     "level": level,
                     "run": run_id,
                     "n_samples": n_samples,
                     "minutes": minutes
                })

runs_df = pd.DataFrame(rows)

# samples per run for each level
samples_per_run_level = runs_df.groupby("level")["n_samples"].agg(["mean", "std"])

# minutes per run for each level
minutes_per_run_level = runs_df.groupby("level")["minutes"].agg(["mean", "std"])

# samples per subject per level
sub_level = (
    runs_df
    .groupby(["subject", "level"])["n_samples"]
    .sum()
    .reset_index(name="n_samples_subject_level")
)
samples_per_subject_level = sub_level.groupby("level")["n_samples_subject_level"].agg(["mean", "std"])


samples_per_run_level["mean±std"] = samples_per_run_level["mean"].round(1).astype(str) + " ± " + samples_per_run_level["std"].round(1).astype(str)

samples_per_subject_level["mean±std"] = samples_per_subject_level["mean"].round(1).astype(str) + " ± " + samples_per_subject_level["std"].round(1).astype(str)

In [3]:
display(samples_per_run_level)

             mean        std      mean±std
level
1      356.133333  26.972124  356.1 ± 27.0
2      389.306667  28.142482  389.3 ± 28.1
3      382.040000  66.353566  382.0 ± 66.4
4      382.133333  64.486188  382.1 ± 64.5

In [4]:
display(samples_per_subject_level)

          mean         std        mean±std
level
1      1068.40   57.825168   1068.4 ± 57.8
2      1167.92   53.562985   1167.9 ± 53.6
3      1146.12   89.952450   1146.1 ± 90.0
4      1146.40  145.040512  1146.4 ± 145.0

In [5]:
display(minutes_per_run_level)

           mean       std
level
1      5.935556  0.449535
2      6.488444  0.469041
3      6.367333  1.105893
4      6.368889  1.074770